language: c
sudo: required

services:
- docker

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq debootstrap
- wget http://ftp.us.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.89_all.deb -O /tmp/debootstrap.deb
- sudo dpkg -i /tmp/debootstrap.deb

script:
- sudo bash scripts/mkrootfs.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ ! -z "$DOCKER_PASSWORD" ]; then
      docker build -f Dockerfile.deploy -t spinlocklabs/chromium-builder-rootfs:latest .;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push spinlocklabs/chromium-builder-rootfs;
    fi
